### ISSUE TITLE
features

### ISSUE THREAD

**Issue by iddq** [urjaman/fast-usbserial#4]
How is it faster and what was the problem with the original usbserial?

**Comment by urjaman** [comment]
This thing can keep up with transferring 2Mbaud both ways at the same time via lots of low-level trickery.

The original usbserial cant keep up with more than 115200 and also happens to misconfigure the USB hardware so that the packet buffers for the IN/OUT endpoints overlap and thus it also corrupts data if you try to use it too full-duplex (not sure if it had other data loss/corruption bugs :P)
